

server:
  port: 8080

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      # show_sql: true
      # format_sql: true

oauth:
  kakao:
    client_id: ecd4743fb9997e0a6eae10908eee37de
    secret_id: qJzb7yQGYpNxBfTzU18maTFV8Zd2LKiY
    redirect_url: http://localhost:8080/auth/kakao

